package com.messagingCluster.Messenger.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.messaging.MessageSecurityMetadataSourceRegistry;
import org.springframework.security.config.annotation.web.socket.AbstractSecurityWebSocketMessageBrokerConfigurer;
import org.springframework.messaging.simp.SimpMessageType;

/**
 * WebSocket Security Configuration for ANonym Messaging
 *
 * This configuration secures WebSocket connections while allowing
 * system-generated messages to pass through for proper connection lifecycle.
 *
 * Security Model:
 * - CONNECT/DISCONNECT/HEARTBEAT: Permitted (system operations)
 * - SUBSCRIBE: Permitted (users can subscribe to their own topics)
 * - MESSAGE (actual chat): Requires authentication via Anonymous Code
 */
@Configuration
public class WebSocketSecurityConfig extends AbstractSecurityWebSocketMessageBrokerConfigurer {

    @Override
    protected void configureInbound(MessageSecurityMetadataSourceRegistry messages) {
        messages
                // 1. SYSTEM OPERATIONS: Allow connection lifecycle events
                // These are generated by the WebSocket framework, not by users
                .simpTypeMatchers(
                        SimpMessageType.CONNECT,      // Initial connection handshake
                        SimpMessageType.CONNECT_ACK,    // Connection established
                        SimpMessageType.HEARTBEAT,    // Keep-alive pings
                        SimpMessageType.UNSUBSCRIBE,  // Topic unsubscription
                        SimpMessageType.DISCONNECT,   // Clean disconnect
                        SimpMessageType.DISCONNECT_ACK // Disconnect acknowledgment
                ).permitAll()

                // 2. SUBSCRIPTION OPERATIONS: Allow users to subscribe to topics
                // Note: Topic-level authorization is enforced in the controller
                .simpDestMatchers("/topic/**", "/user/**", "/queue/**").permitAll()

                // 3. MESSAGE OPERATIONS: Require authentication for actual messages
                // This is where users send chat messages - must be authenticated
                .simpTypeMatchers(SimpMessageType.MESSAGE).authenticated()

                // 4. SUBSCRIBE with authentication: Ensure users are authenticated when subscribing
                .simpTypeMatchers(SimpMessageType.SUBSCRIBE).authenticated()

                // 5. FALLBACK: Deny anything not explicitly permitted
                .anyMessage().denyAll();
    }

    /**
     * Disable same-origin checks to allow cross-origin WebSocket connections
     * This is necessary for mobile apps and different domain access
     *
     * Security Note: We handle authentication via Anonymous Code headers,
     * not through browser-based same-origin policies
     */
    @Override
    protected boolean sameOriginDisabled() {
        return true;
    }
}